name: qaqc
channels: [conda-forge]
dependencies:
  - python=3.11
  - numpy
  - pandas
  - geopandas
  - rasterio
  - shapely
  - scipy
  - folium
  - pillow
  - matplotlib
  - affine
  - scikit-image
  - pip
  - pip:
      - streamlit
      - streamlit-folium
      - typer                 # <-- add this
