name: CI

on:
  push:
  pull_request:

jobs:
  lint-and-import:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install minimal deps
        run: |
          python -m pip install --upgrade pip
          pip install typer rich
          # soft import test for package (no heavy geodeps)
          python - <<'PY'
          import importlib
          for m in ["survey_surface.cli"]:
              importlib.import_module(m)
          print("ok")
          PY
