name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: latest             # <-- valid values: latest or 1.2.3-0 style
          environment-file: environment.yml      # must exist and include "name: qaqc"
          environment-name: qaqc                 # optional; overrides name in file
          cache-environment: true
          cache-downloads: true
          create-args: >-
            python=3.11

      - name: Show environment
        run: micromamba run -n qaqc bash -lc "python -V && which python"

      - name: Install package (editable)
        run: micromamba run -n qaqc pip install -e .[app]

      - name: Mini pipeline smoke test
        run: |
          micromamba run -n qaqc python - <<'PY'
          import numpy as np
          from pathlib import Path
          from affine import Affine
          from survey_surface.grid import write_geotiff
          from survey_surface.contours import contours_geojson_from_raster
          Path("outputs").mkdir(exist_ok=True)
          arr = (np.random.rand(60, 60) * 12.0 + 500.0)
          transform = Affine.translation(500000, 2500000) * Affine.scale(2.0, -2.0)
          write_geotiff("outputs/dem.tif", arr, transform, "EPSG:32638")
          contours_geojson_from_raster("outputs/dem.tif", 1.0, "outputs/contours.geojson")
          print("OK: wrote outputs/dem.tif and outputs/contours.geojson")
          PY

      - name: CLI import (sanity)
        run: micromamba run -n qaqc python -c "import importlib; importlib.import_module('survey_surface.cli'); print('CLI import OK')"
