[theme]
base = "dark"
primaryColor = "#60a5fa"
backgroundColor = "#0b1220"
secondaryBackgroundColor = "#111827"
textColor = "#e5e7eb"
font = "sans serif"

[server]
enableXsrfProtection = true
enableCORS = true
